version: '3.1'

services:
  db:
    container_name: pg-container
    build: src/db/.docker
    restart: always
    environment:
      POSTGRES_DB: 'fx-fiber-db'
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data